"component : spring-batch":
  - changed-files:
      - any-glob-to-any-file: 'batch-boot-jpa-sample/**/*'
"component : archunit":
  - changed-files:
      - any-glob-to-any-file: 'boot-api-archunit-sample/**/*'
"component : chaos-monkey":
  - changed-files:
      - any-glob-to-any-file: 'boot-chaos-monkey/**/*'
"component : grafana-lgtm":
  - changed-files:
      - any-glob-to-any-file: 'boot-grafana-lgtm/**/*'
"component: mongodb-elasticsearch":
  - changed-files:
      - any-glob-to-any-file: 'boot-mongodb-elasticsearch/**/*'
"component: opensearch":
  - changed-files:
      - any-glob-to-any-file: 'boot-opensearch-sample/**/*'
"component: rabbitmq-thymeleaf":
  - changed-files:
      - any-glob-to-any-file: 'boot-rabbitmq-thymeleaf/**/*'
"component: rest-docs":
  - changed-files:
      - any-glob-to-any-file: 'boot-rest-docs-sample/**/*'
"component: strategy-plugin":
  - changed-files:
      - any-glob-to-any-file: 
          - boot-strategy-plugin/**/*
"component: togglz":
  - changed-files:
      - any-glob-to-any-file:
          - boot-togglz-sample/**/*
"component: ultimate-redis":
  - changed-files:
      - any-glob-to-any-file:
          - boot-ultimate-redis/**/*
"component: graphql-webflux":
  - changed-files:
      - any-glob-to-any-file: 
          - graphql/boot-graphql-webflux/**/*
"component: graphql-webmvc":
  - changed-files:
      - any-glob-to-any-file:
          - graphql/boot-graphql-webmvc/**/*
"component: graphql-querydsl":
  - changed-files:
      - any-glob-to-any-file:
          - graphql/boot-graphql-querydsl/**/*
"component: httpclients":
  - changed-files:
      - any-glob-to-any-file:
          - httpClients/boot-http-proxy/**/*
          - httpClients/boot-rest-template/**/*
          - httpClients/boot-restclient/**/*
          - httpClients/boot-web-client-mvc/**/*
          - httpClients/boot-web-client-webflux/**/*
"component: jmh-benchmark":
  - changed-files:
      - any-glob-to-any-file:
          - jmh-benchmark/**/*
"component: customsequence":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-data-customsequence/**/*
"component: data-envers":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-data-envers/**/*
"component: multiple-datasources":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-data-multipledatasources/**/*
"component: hibernate2ndlevelcache-sample":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-hibernate2ndlevelcache-sample/**/*
"component: jpa-jooq":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-jpa-jooq-sample/**/*
"component: jpa-lock":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-jpa-locks/**/*
"component: read-replica-postgres":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/boot-read-replica-postgresql/**/*
"component: keyset-pagination-blaze":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/keyset-pagination/blaze-persistence/**/*
"component: keyset-pagination-data-jpa":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/keyset-pagination/boot-data-window-pagination/**/*
"component: jpa-multitenancy":
  - changed-files:
      - any-glob-to-any-file:
          - jpa/multitenancy/**/*
"component: openapi":
  - changed-files:
      - any-glob-to-any-file:
          - open-api-spring-boot/**/*
"component: r2dbc":
  - changed-files:
      - any-glob-to-any-file:
          - r2dbc/boot-jooq-r2dbc-sample/**/*
          - r2dbc/boot-r2dbc-sample/**/*
          - r2dbc/boot-r2dbc-reactive-cache/**/*
"component: jobrunr":
  - changed-files:
      - any-glob-to-any-file:
          - scheduler/boot-scheduler-jobrunr/**/*
"component: quartz":
  - changed-files:
      - any-glob-to-any-file:
          - scheduler/boot-scheduler-quartz/**/*
"component: shedlock":
  - changed-files:
      - any-glob-to-any-file:
          - scheduler/boot-scheduler-shedlock/**/*
"type: documentation": 
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
"type: dependency-upgrade":
  - changed-files:
      - any-glob-to-any-file:
          - batch-boot-jpa-sample/pom.xml
          - boot-api-archunit-sample/pom.xml
          - boot-chaos-monkey/pom.xml
          - boot-mongodb-elasticsearch/pom.xml
          - boot-opensearch-sample/pom.xml
          - boot-rabbitmq-thymeleaf/pom.xml
          - boot-rest-docs-sample/pom.xml
          - boot-strategy-plugin/pom.xml
          - boot-togglz-sample/pom.xml
          - boot-ultimate-redis/pom.xml
          - graphql/boot-graphql-querydsl/pom.xml
          - graphql/boot-graphql-webflux/pom.xml
          - graphql/boot-graphql-webmvc/pom.xml
          - httpClients/boot-http-proxy/pom.xml
          - httpClients/boot-rest-template/pom.xml
          - httpClients/boot-restclient/pom.xml
          - httpClients/boot-web-client-mvc/pom.xml
          - httpClients/boot-web-client-webflux/pom.xml
          - jmh-benchmark/pom.xml
          - jpa/boot-data-customsequence/pom.xml
          - jpa/boot-data-envers/pom.xml
          - jpa/boot-data-multipledatasources/pom.xml
          - jpa/boot-hibernate2ndlevelcache-sample/pom.xml
          - jpa/boot-jpa-jooq-sample/pom.xml
          - jpa/boot-data-jpa-locks/pom.xml
          - jpa/boot-read-replica-postgresql/pom.xml
          - jpa/keyset-pagination/blaze-persistence/pom.xml
          - jpa/keyset-pagination/boot-data-window-pagination/pom.xml
          - jpa/multitenancy/multitenancy-db/pom.xml
          - jpa/multitenancy/multidatasource-multitenancy/pom.xml
          - jpa/multitenancy/partition/pom.xml
          - jpa/multitenancy/schema/pom.xml
          - open-api-spring-boot/pom.xml
          - r2dbc/boot-jooq-r2dbc-sample/pom.xml
          - r2dbc/boot-r2dbc-sample/pom.xml
          - r2dbc/boot-r2dbc-reactive-cache/pom.xml
          - scheduler/boot-scheduler-jobrunr/pom.xml
          - scheduler/boot-scheduler-quartz/pom.xml
          - scheduler/boot-scheduler-shedlock/pom.xml
