global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'boot-grafana-lgtm'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'boot-grafana-lgtm'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          application: 'prometheus'