version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=user
      - MYSQL_DATABASE=mydatabase

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydatabase

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning

  jenkins:
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - "8080:8080"
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
