spring:
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/test
logging:
  level:
    org:
      springframework:
        data.mongodb: INFO
        boot.autoconfigure.mongo: INFO
    com.mongodb.client: INFO
