spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/test
logging:
  level:
    org:
      springframework:
        data.mongodb: INFO
        boot.autoconfigure.mongo: INFO
    com.mongodb.client: INFO
