services:
  postgres:
    container_name: postgres_local_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesDB
    ports:
      - "5432:5432"
    volumes:
      - local_dev:/var/lib/postgresql/data
  redis:
    container_name: redis_local_db
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
   local_dev: