global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'strategy-plugin-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]