version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=memberdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres-db:/var/lib/postgresql/data
  
  mysql:
    image: mysql:latest
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cardholderdb
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
      # Password for root access
      - MYSQL_ROOT_PASSWORD=password
    
    # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
  postgres-db:
    driver: local