version: '3.8'
services:

  grafanalgtm:
    image: grafana/otel-lgtm:0.7.1
    extra_hosts: ['host.docker.internal:host-gateway']
    container_name: grafanalgtm
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=500
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus:v2.54.1
    extra_hosts: ['host.docker.internal:host-gateway']
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1