spring:
  primary:
    datasource:
      password: postgres_write
      username: postgres_write
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/my_database
  replica:
    datasource:
      password: repl_password
      username: repl_user
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:15432/my_database

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog.sql