version: "3.2"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.6-management
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 350m
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge