name: boot-ultimate-redis

on:
  push:
    paths:
      - "boot-ultimate-redis/**"
    branches: [main]
  pull_request:
    paths:
      - "boot-ultimate-redis/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: boot-ultimate-redis

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=rajadilipkolli_my-spring-boot-experiments
