name: boot-ultimate-redis

on:
  push:
    paths:
      - "boot-ultimate-redis/**"
    branches: [main]
  pull_request:
    paths:
      - "boot-ultimate-redis/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: boot-ultimate-redis

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: "21"
          distribution: "microsoft"
          cache: "maven"
      - name: Build with Maven
        run: ./mvnw clean verify
