name: Dev Branch CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'release*'

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
