name: boot-data-customsequence

on:
  push:
    paths:
      - "jpa/boot-data-customsequence/**"
    branches: [main]
  pull_request:
    paths:
      - "jpa/boot-data-customsequence/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "jpa/boot-data-customsequence"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=rajadilipkolli_my-spring-boot-experiments
