name: boot-jobrunr-sample

on:
  push:
    paths:
      - "scheduler/boot-jobrunr-sample/**"
    branches: [main]
  pull_request:
    paths:
      - "scheduler/boot-jobrunr-sample/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scheduler/boot-jobrunr-sample
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"
      - name: Build and analyze
        run: ./mvnw clean verify
