name: spring-boot-jpa-multitenancy-schema

on:
  push:
    paths:
      - "jpa/spring-boot-jpa-multitenancy/schema/**"
    branches: [main]
  pull_request:
    paths:
      - "jpa/spring-boot-jpa-multitenancy/schema/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "jpa/spring-boot-jpa-multitenancy/schema"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven
        run: ./mvnw clean verify
