name: spring-boot-strategy-plugin-non-native

on:
  push:
    paths:
      - "spring-boot-strategy-plugin/**"
    branches: [main]
  pull_request:
    paths:
      - "spring-boot-strategy-plugin/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spring-boot-strategy-plugin
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 18
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 18
          distribution: "zulu"
          cache: "gradle"

      - name: Build and analyze
        run: ./gradlew clean build --info
